### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by danielhers** [DreamerDeo/HIT-SCIR-CoNLL2019#1]
Are the trained models used to parse the results submitted to the CoNLL 2019 shared task available for download?

**Comment by longxudou** [comment]
Hi, Daniel

We have uploaded our model on [Google Drive](https://drive.google.com/open?id=1SbtqPdNYZWY9m2cDo58tNuzCFtKUMSj1).

For prediction, please specify the BERT path in `config.json` to import the bert-indexer and bert-embedder under Allennlp. More prediction commands could be found in `bash/predict.sh`.

About BERT version, DM/PSD/UCCA/EDS use cased_L-12_H-768_A-12 (cased-bert-base) and AMR uses wwm_cased_L-24_H-1024_A-16 (wwm-cased-bert-large). 


Best,
Longxu

**Comment by danielhers** [comment]
This is great, thank you!
