### ISSUE TITLE
Let's push the boundaries of the state of the art once again! 

### ISSUE THREAD

**Issue by LifeIsStrange** [DreamerDeo/HIT-SCIR-CoNLL2019#10]
By using XLnet instead of BERT :}
XLnet outperforms BERT on most tasks by a large margin. 
You could use for example https://github.com/huggingface/transformers
So that you could easily switch to yet another pre trainer in a few years simply by changing a line or two and keeping the same API

**Comment by longxudou** [comment]
Thanks for your advice!

We will use more powerful pre-trained models, like xlnet, roberta, in our following work. 
In this year, we will push this system further along with the conll2020 share task.

Best,
Longxu

**Comment by LifeIsStrange** [comment]
Nice to hear that!
You might also be interested by https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer
which is the state of the art optimizer, it can be seen as the successor of Adam. 
There is also the Mish activation function that often outperform Relu https://github.com/digantamisra98/Mish

**Comment by LifeIsStrange** [comment]
@DreamerDeo so has there been any progress?

**Comment by longxudou** [comment]
We are still working on conll2020 shared task and see a lot gain from more powerful pretrained models. Moreover, we have improved our public platform ltp(Language Technology Platform) [https://github.com/HIT-SCIR/ltp](https://github.com/HIT-SCIR/ltp). If your are interested, please have a look~

The ddl of conll2020 is 8/10. We will release the final model and system description after that.
