### ISSUE TITLE
No "anchors" key in evaluation UDPipe file

### ISSUE THREAD

**Issue by ZhaofengWu** [DreamerDeo/HIT-SCIR-CoNLL2019#5]
I'm trying to add UDPipe information into the evaluation data using `preprocess_eval.py`.

This line

https://github.com/DreamerDeo/HIT-SCIR-CoNLL2019/blob/9bc3c0727c13aac72e71ae7bf48cc195f481bffa/toolkit/preprocess_eval.py#L10

looks for the `"anchors"` key under a UDPipe node. But it seems that the `evaluation/udpipe.mrp` file doesn't have this `"anchors"` key under nodes. Do you know what is happening? `companion/udpipe.mrp` does have that key though.

**Comment by longxudou** [comment]
Hi,

We have checked our evaluation data. The anchors information is listed in `evaluation/udpipe.mrp`.
And we found the overview and release history in `evaluation/README.udpipe.txt:`

Overview

> This directory contains a re-release of the morpho-syntactic compantion trees
> for the MRP 2019 shared task, i.e. tokenized and syntactically parsed parser
> inputs.  A re-release of this part of the evaluation package was required to
> augment the companion trees with anchoring information, i.e. character start
> and end indices into the original input string.

 Release History

> [Version 1.1; July 15, 2019]
> 
> + Re-release of companion trees only, now including anchoring.
> 
> [Version 1.0; July 1, 2019]
> 
> + First release of MRP 2019 training data in all frameworks.


It seems that you need to update the evaluation data to v1.1.

**Comment by ZhaofengWu** [comment]
That worked, thank you!
