### ISSUE TITLE
Does this only use tokenization from the companion file?

### ISSUE THREAD

**Issue by ZhaofengWu** [DreamerDeo/HIT-SCIR-CoNLL2019#6]
Hi, I asked this question as a comment [under another thread](https://github.com/DreamerDeo/HIT-SCIR-CoNLL2019/issues/3#issuecomment-612681009), but since it was a closed issue, I don't know if it'll be picked up. I hope you don't mind if I ask it again here. Is it true that during both training and evaluation, the only thing you took from the companions is the tokenization?

**Comment by longxudou** [comment]
Hi,

For AMR, the tokenization is computed by JAMR. 
For DM/PSD/EDS/UCCA, we directly adopt the tokenization from companions. 
(Tokenization is used to compute the anchor of each nodes. )

The dataset reader also extracts pos-tag and lemmatization from companion. But we didn't use that finally, given that the information (predicted by UDPipe) are not totally correct.

**Comment by ZhaofengWu** [comment]
Thanks, and is it the same for dependency parse (read by dataset reader but not used)?

**Comment by longxudou** [comment]
Yes, we don't use the dependency parse. The only thing we use is the tokenization.

**Comment by ZhaofengWu** [comment]
Great, thanks a lot!
