### ISSUE TITLE
A bug in the EDS predictor?

### ISSUE THREAD

**Issue by ZhaofengWu** [DreamerDeo/HIT-SCIR-CoNLL2019#7]
https://github.com/DreamerDeo/HIT-SCIR-CoNLL2019/blob/9bc3c0727c13aac72e71ae7bf48cc195f481bffa/utils/transition_eds_predictor.py#L228-L230

Should this be the following?
```
 for value_sp in value.lower().split(): 
     if value_sp in month_dict: 
         value = month_dict[value_sp] 
```
===========
In general, the `predict_batch_instance` functions across the predictors hide errors from `*_trans_outputs_into_mrp` functions because the use of `try-except`. Is it possible to remove those `try-except` statements to better catch errors? In this case for example, the program output `[]` which caused my downstream scripts to break, which led me to investigate the error and found this. If the predictor throws an error it'd be faster and easier to identify the issue.

Thanks!

**Comment by ZhaofengWu** [comment]
And I'd be happy to submit a PR for these two things if you'd like

**Comment by longxudou** [comment]
Hi,

I have fixed the bug you mentioned in eds predictor and commit it. As for try-except, we only debug it in conll2019 dataset previouly. 

As you said, it's a better way to remove those statement for faster error identification. We will update those parts in the current conll2020 shared task code.

**Comment by ZhaofengWu** [comment]
Thanks! Just FYI, in https://github.com/DreamerDeo/HIT-SCIR-CoNLL2019/commit/0b6bfdac4902fd1849b26931e9dd00644d47d05b, I think you need to change `value` to `value_sp` in the `if` condition too, right?

**Comment by longxudou** [comment]
Hi, I have fixed it and check the correctness on mrp2019 eds dataset. 

Currently, there are only 2 bad cases  in 'mofy' label since we simply choose the back one in our setting.
Input#Output#Gold
September-October#Oct#Sep
January-June#Jun#Jan

**Comment by ZhaofengWu** [comment]
Thanks!
